"""Rule codes and the RuleMatch result type shared by every built-in rule."""

from __future__ import annotations

from dataclasses import dataclass

from howlwriter.domain.serialization import DataClassSerializationMixin

AI_STYLE_BANNED_WORD = "AI_STYLE_BANNED_WORD"
AI_STYLE_NOT_X_BUT_Y = "AI_STYLE_NOT_X_BUT_Y"
AI_STYLE_EMPTY_TRANSITION = "AI_STYLE_EMPTY_TRANSITION"
AI_STYLE_CANNED_OPENING = "AI_STYLE_CANNED_OPENING"
AI_STYLE_CANNED_CONCLUSION = "AI_STYLE_CANNED_CONCLUSION"
AI_STYLE_GENERIC_TRANSITION = "AI_STYLE_GENERIC_TRANSITION"
AI_STYLE_FORMULAIC_CONTRAST = "AI_STYLE_FORMULAIC_CONTRAST"
AI_STYLE_GENERIC_INTENSIFIER = "AI_STYLE_GENERIC_INTENSIFIER"
AI_STYLE_CORPORATE_FILLER = "AI_STYLE_CORPORATE_FILLER"
AI_STYLE_REPETITIVE_TRICOLON = "AI_STYLE_REPETITIVE_TRICOLON"
AI_STYLE_EXCESSIVE_EM_DASH = "AI_STYLE_EXCESSIVE_EM_DASH"
AI_STYLE_EXCESSIVE_HEADINGS = "AI_STYLE_EXCESSIVE_HEADINGS"
AI_STYLE_EXCESSIVE_BOLD = "AI_STYLE_EXCESSIVE_BOLD"
AI_STYLE_REPETITIVE_PARAGRAPH_STRUCTURE = "AI_STYLE_REPETITIVE_PARAGRAPH_STRUCTURE"
AI_STYLE_EXCESSIVE_RHETORICAL_QUESTIONS = "AI_STYLE_EXCESSIVE_RHETORICAL_QUESTIONS"
AI_STYLE_REPETITIVE_MINI_CONCLUSION = "AI_STYLE_REPETITIVE_MINI_CONCLUSION"
AI_STYLE_PARAGRAPH_LENGTH_SYMMETRY = "AI_STYLE_PARAGRAPH_LENGTH_SYMMETRY"
AI_STYLE_ENGAGEMENT_BAIT = "AI_STYLE_ENGAGEMENT_BAIT"
AI_STYLE_FAKE_RHETORICAL_HOOK = "AI_STYLE_FAKE_RHETORICAL_HOOK"
AI_STYLE_HASHTAG_SPAM = "AI_STYLE_HASHTAG_SPAM"
AI_STYLE_EMOJI_BULLETS = "AI_STYLE_EMOJI_BULLETS"
AI_STYLE_MOTIVATIONAL_SLOP = "AI_STYLE_MOTIVATIONAL_SLOP"

# Maps a config.banned_patterns entry to the rule code it activates. A
# pattern name with no entry here is inert -- see linting/engine.py.
PATTERN_KEY_TO_RULE_CODE = {
    "not_x_but_y": AI_STYLE_NOT_X_BUT_Y,
    "empty_transition": AI_STYLE_EMPTY_TRANSITION,
    "canned_opening": AI_STYLE_CANNED_OPENING,
    "canned_conclusion": AI_STYLE_CANNED_CONCLUSION,
    "generic_transition": AI_STYLE_GENERIC_TRANSITION,
    "formulaic_contrast": AI_STYLE_FORMULAIC_CONTRAST,
    "generic_intensifier": AI_STYLE_GENERIC_INTENSIFIER,
    "corporate_filler": AI_STYLE_CORPORATE_FILLER,
    "repetitive_tricolon": AI_STYLE_REPETITIVE_TRICOLON,
    "excessive_em_dash": AI_STYLE_EXCESSIVE_EM_DASH,
    "excessive_headings": AI_STYLE_EXCESSIVE_HEADINGS,
    "excessive_bold": AI_STYLE_EXCESSIVE_BOLD,
    "repetitive_paragraph_structure": AI_STYLE_REPETITIVE_PARAGRAPH_STRUCTURE,
    "excessive_rhetorical_questions": AI_STYLE_EXCESSIVE_RHETORICAL_QUESTIONS,
    "repetitive_mini_conclusion": AI_STYLE_REPETITIVE_MINI_CONCLUSION,
    "paragraph_length_symmetry": AI_STYLE_PARAGRAPH_LENGTH_SYMMETRY,
    "engagement_bait": AI_STYLE_ENGAGEMENT_BAIT,
    "fake_rhetorical_hook": AI_STYLE_FAKE_RHETORICAL_HOOK,
    "hashtag_spam": AI_STYLE_HASHTAG_SPAM,
    "emoji_bullets": AI_STYLE_EMOJI_BULLETS,
    "motivational_slop": AI_STYLE_MOTIVATIONAL_SLOP,
}


@dataclass
class RuleMatch(DataClassSerializationMixin):
    rule_code: str
    matched_text: str
    message: str
    paragraph_index: int | None = None
    sentence_index: int | None = None
    severity: str = "warning"
