"""Stage 3: separate the prose the author wrote from everything around it.

A graduate paper is mostly not the author's voice. Title-page fields, a table
of contents, the assignment prompt pasted at the top, block quotations, code
listings, and a References section are all text in the file, and every one of
them would distort the statistics: a reference list alone can wreck mean
sentence length, lexical diversity, and punctuation rates at once.

The rule that shapes this module is the one that is easy to get wrong in the
other direction. A sentence that CITES a source is still the author's
sentence:

    The results from Smith (2024) suggest that the control is useful, but the
    small sample makes that conclusion difficult to generalize.

That stays. Only a citation standing alone as its own block, or an entry in a
reference list, is apparatus. Losing authored prose because it happens to
contain a year in parentheses would be a worse failure than keeping a stray
reference line, so every rule here is written to err toward keeping.
"""

from __future__ import annotations

from dataclasses import dataclass, field
import re

#: Headings that begin a section whose entire remaining content is apparatus.
_TERMINAL_SECTION = re.compile(
    r"^\s*(?:#+\s*)?(?:\d+[.)]\s*)?"
    r"(references?|bibliography|works\s+cited|reference\s+list|citations?|"
    r"appendix(?:\s+[a-z0-9]+)?|appendices)\s*:?\s*$",
    re.IGNORECASE,
)

#: A table of contents heading. Its section ends at the next real heading.
_TOC_HEADING = re.compile(
    r"^\s*(?:#+\s*)?(table\s+of\s+contents|contents|outline)\s*:?\s*$", re.IGNORECASE
)

#: Title-page and cover-sheet fields: a short label, a colon, a short value.
_COVER_FIELD = re.compile(
    r"^\s*(name|student|student\s+name|course|course\s+(?:number|title|code)|"
    r"instructor|professor|teacher|date|due(?:\s+date)?|semester|term|section|"
    r"assignment|university|college|school|department|program|id|student\s+id|"
    r"email|submitted\s+(?:to|by)|title|subject|class|credits?|week)\s*:\s*(.{0,80})$",
    re.IGNORECASE,
)

#: Lab-tool and LMS report furniture. These are generated by the platform,
#: not written by the student, and they cluster at the top of exported PDFs.
_GENERATED_BOILERPLATE = re.compile(
    r"^\s*(report\s+generated|time\s+on\s+task|progress|score|grade|points\s+(?:earned|possible)|"
    r"attempt\s+\d|submission\s+(?:id|date)|page\s+\d+\s+of\s+\d+|copyright|"
    r"all\s+rights\s+reserved|jones\s*&\s*bartlett|printed\s+on|generated\s+(?:on|by)|"
    r"lab\s+report|section\s+\d+\s*:\s*(?:hands-on|deliverables|assessment))\b",
    re.IGNORECASE,
)

#: Strong assignment-prompt and rubric markers. Every one of these is
#: instruction-to-the-student language that a student does not write about
#: their own work, which is what makes them safe to key on.
_PROMPT_MARKERS = (
    "in this assignment", "for this assignment", "this assignment requires",
    "your paper should", "your essay should", "your report should",
    "your submission", "you will be graded", "you are required to",
    "you must submit", "please submit", "submit your", "upload your",
    "learning objective", "learning outcome", "grading criteria",
    "grading rubric", "rubric", "points possible", "worth of your grade",
    "% of your grade", "deliverable(s)", "assignment instructions",
    "assignment overview", "assignment description", "instructions:",
    "requirements:", "deliverables:", "objectives:", "answer the following",
    "complete the following", "in your own words, explain",
    "minimum of", "no more than", "double-spaced", "apa format",
    "apa 7th", "times new roman", "12-point font", "cite at least",
    "must include at least", "due by", "late submissions",
)

#: An APA-ish reference entry: surname-initial authorship then a year.
_REFERENCE_ENTRY = re.compile(
    r"^\s*[A-Z][\w'’-]+,\s*(?:[A-Z]\.\s*){1,4}"
    r"(?:(?:,|&|and)\s*[A-Z][\w'’-]+,\s*(?:[A-Z]\.\s*){1,4})*"
    r".{0,40}\(\s*(?:n\.d\.|\d{4}[a-z]?)\s*\)",
)

#: A block that is only a citation, a bare URL, or a DOI.
_CITATION_ONLY = re.compile(
    r"^\s*(?:\(?[A-Z][\w'’-]+(?:\s+(?:et\s+al\.?|&|and)\s+[A-Z][\w'’-]+)*,?\s*"
    r"\d{4}[a-z]?(?:,\s*(?:p{1,2}\.\s*\d+(?:[-–]\d+)?))?\)?[.;,]?|"
    r"(?:https?://|doi:|www\.)\S+|"
    r"\[\d+\]\s*.{0,120})\s*$",
    re.IGNORECASE,
)

_URL_OR_DOI = re.compile(r"https?://|doi\.org/|doi:\s*10\.", re.IGNORECASE)
_HEADING = re.compile(r"^\s*#{1,6}\s+\S")
_LIST_ITEM = re.compile(r"^\s*(?:[-*+•]|\d+[.)])\s+")
_TABLE_ROW = re.compile(r"^\s*\|.*\|\s*$")
_BLOCK_QUOTE = re.compile(r"^\s*>")
_FENCE = re.compile(r"^\s*(?:```|~~~)")
_TOC_ENTRY = re.compile(r"^\s*\S.*?(?:\.{4,}|\t|\s{4,})\s*\d+\s*$")
_SENTENCE_END = re.compile(r"[.!?][\"')\]]?\s*$")
_WORD = re.compile(r"[A-Za-z][A-Za-z'’-]*")

#: A quotation long enough that its style is the quoted author's, not ours.
_LONG_QUOTE_WORDS = 25

#: A block shorter than this that never reaches a sentence ending is a label
#: or a fragment, not authored prose.
_MIN_PROSE_WORDS = 5


@dataclass
class RemovedBlock:
    kind: str
    words: int


@dataclass
class CleanupResult:
    """Authored prose, plus an account of what was taken out and why."""

    text: str = ""
    headings: list[str] = field(default_factory=list)
    kept_words: int = 0
    removed_words: int = 0
    removed_kinds: dict[str, int] = field(default_factory=dict)
    removed_blocks: list[RemovedBlock] = field(default_factory=list)
    list_items: int = 0
    total_blocks: int = 0

    @property
    def apparatus_ratio(self) -> float:
        """Share of the document's words that were not authored prose.

        A document that is nearly all apparatus is a form or a template, and
        `quality.py` uses this to say so.
        """
        total = self.kept_words + self.removed_words
        return (self.removed_words / total) if total else 0.0


def _word_count(text: str) -> int:
    return len(_WORD.findall(text))


def _looks_like_prompt(block: str) -> bool:
    lowered = block.lower()
    hits = sum(1 for marker in _PROMPT_MARKERS if marker in lowered)
    if hits >= 2:
        return True
    # A single very strong marker is enough when the block reads as an
    # instruction: second person, imperative, and no first-person reflection.
    if hits == 1:
        second_person = len(re.findall(r"\byou(?:r|rs)?\b", lowered))
        first_person = len(re.findall(r"\b(?:i|we|my|our)\b", lowered))
        if second_person >= 2 and second_person > first_person:
            return True
    return False


def _is_cover_field(block: str) -> bool:
    """True when every line of the block is a cover-sheet field.

    Cover sheets usually arrive as one block of consecutive short lines
    ("Name: ...", "Course: ...", "Date: ..."), so the whole block has to
    qualify -- one field line inside a paragraph of prose must not condemn
    the paragraph.
    """
    lines = [line for line in block.strip().splitlines() if line.strip()]
    if not lines:
        return False
    for line in lines:
        match = _COVER_FIELD.match(line.strip())
        if not match:
            return False
        # "Instructions: write four pages" is a prompt, not a cover field; a
        # real cover field's value is a name or a date, so it stays short.
        if _word_count(match.group(2) or "") > 12:
            return False
    return True


def _is_reference_entry(block: str) -> bool:
    if _REFERENCE_ENTRY.match(block):
        return True
    # A bare title-plus-locator line with no sentence structure.
    if _URL_OR_DOI.search(block) and not _SENTENCE_END.search(block):
        return _word_count(block) < 40
    return False


def _classify(block: str, *, index: int, total: int) -> str | None:
    """Return the apparatus kind for a block, or None to keep it."""
    stripped = block.strip()
    if not stripped:
        return "blank"

    if _FENCE.match(stripped):
        return "code_block"
    if _BLOCK_QUOTE.match(stripped):
        return "block_quote"
    if _TABLE_ROW.match(stripped.splitlines()[0]):
        return "table"
    if _GENERATED_BOILERPLATE.match(stripped):
        return "generated_boilerplate"
    if _TOC_ENTRY.match(stripped):
        return "table_of_contents"

    # Cover-sheet fields only count as such near the front of the document;
    # "Date: ..." halfway through a paper is more likely authored content.
    if _is_cover_field(stripped) and index < max(8, total // 10):
        return "title_page"

    if _is_reference_entry(stripped):
        return "reference_entry"
    if _CITATION_ONLY.match(stripped):
        return "citation_only"
    if _looks_like_prompt(stripped):
        return "rubric_or_prompt"

    words = _word_count(stripped)

    # A long fully-quoted passage is the quoted author's prose.
    if words >= _LONG_QUOTE_WORDS:
        quoted = re.match(r'^\s*["“].*["”]\s*(?:\([^)]*\))?\s*$', stripped, re.S)
        if quoted:
            return "long_quotation"

    if _HEADING.match(stripped):
        return None  # kept, but reported separately
    if words < _MIN_PROSE_WORDS and not _SENTENCE_END.search(stripped):
        return "fragment_or_label"
    return None


def clean_document(text: str) -> CleanupResult:
    """Strip academic apparatus, keeping the author's own sentences.

    Headings are kept in the returned text so heading frequency stays
    measurable; `features.py` separates them from sentence statistics.
    """
    blocks = re.split(r"\n\s*\n", text.replace("\r\n", "\n").replace("\r", "\n"))
    result = CleanupResult(total_blocks=len(blocks))

    kept: list[str] = []
    in_terminal_section = False
    in_toc = False
    in_fence = False

    for index, block in enumerate(blocks):
        stripped = block.strip()
        if not stripped:
            continue

        first_line = stripped.splitlines()[0]

        # A fenced code block can span blank lines; stay inside it until it
        # closes so its contents never reach the statistics.
        if _FENCE.match(first_line):
            in_fence = not in_fence or _FENCE.search(stripped[3:]) is None
            result.removed_words += _word_count(stripped)
            _record(result, "code_block", _word_count(stripped))
            continue
        if in_fence:
            result.removed_words += _word_count(stripped)
            _record(result, "code_block", _word_count(stripped))
            continue

        # Once a References/Bibliography/Appendix heading is seen, the rest of
        # the document is apparatus. This is the single highest-value rule
        # here: a reference list is dense, uniform, and utterly unlike prose.
        if _TERMINAL_SECTION.match(first_line):
            in_terminal_section = True
            _record(result, "references_section", _word_count(stripped))
            result.removed_words += _word_count(stripped)
            continue
        if in_terminal_section:
            # A first-level heading that is clearly a new content section can
            # end an appendix; a references list never resumes prose.
            _record(result, "references_section", _word_count(stripped))
            result.removed_words += _word_count(stripped)
            continue

        if _TOC_HEADING.match(first_line):
            in_toc = True
            _record(result, "table_of_contents", _word_count(stripped))
            result.removed_words += _word_count(stripped)
            continue
        if in_toc:
            if _HEADING.match(first_line) and not _TOC_ENTRY.match(first_line):
                in_toc = False
            else:
                _record(result, "table_of_contents", _word_count(stripped))
                result.removed_words += _word_count(stripped)
                continue

        kind = _classify(stripped, index=index, total=len(blocks))
        if kind is not None:
            _record(result, kind, _word_count(stripped))
            result.removed_words += _word_count(stripped)
            continue

        if _HEADING.match(first_line):
            result.headings.append(re.sub(r"^\s*#+\s*", "", first_line).strip())
        if _LIST_ITEM.match(first_line):
            result.list_items += 1

        kept.append(stripped)
        result.kept_words += _word_count(stripped)

    result.text = "\n\n".join(kept)
    return result


def _record(result: CleanupResult, kind: str, words: int) -> None:
    result.removed_kinds[kind] = result.removed_kinds.get(kind, 0) + 1
    result.removed_blocks.append(RemovedBlock(kind=kind, words=words))
